### ISSUE TITLE
Broken in Ruby >= 3.0?

### ISSUE THREAD

**Issue by pilaf** [haines/yard-relative_markdown_links#174]
I was having trouble getting this to work on my project, so I cloned your example project haines/rake-multilogs and saw that it worked fine there. Narrowing down the differences between my project and rake-multilogs I arrived at the Ruby version being the main difference. On Ruby 2.7.2 (as rake-multilogs wants) it seems to work fine, but on my project that's using Ruby 3.1 it fails. As an experiment I downgraded my project to Ruby 2.7.2 and suddenly it started working.

**Comment by haines** [comment]
Thanks for reporting @pilaf, and sorry for the slow response. It seems like this is due to a change in recent versions of the RDoc markdown processor (if you use e.g. commonmarker instead it works fine). I've pushed v0.5.0 with a workaround.
