### ISSUE TITLE
could not success start

### ISSUE THREAD

**Issue by 7dir** [haines/yard-relative_markdown_links#5]
Hello!

Please `.yardopts` example

**Comment by haines** [comment]
Hi @7dir, the minimum .yardopts would be something like 

```
--plugin relative_markdown_links
-
**/*.md
```

You'll also need to install the gem - either run `gem install yarn-relative_markdown_links`, or add `gem "yarn-relative_markdown_links"` to your Gentile and then run `bundle install`.

I'm using this gem on another project here, if you want to see a working example: https://github.com/haines/rake-multilogs

**Comment by 7dir** [comment]
thnx a lot
